services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: datatripwire
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - datatripwire_pgdata:/var/lib/postgresql/data

volumes:
  datatripwire_pgdata:
